#!/bin/bash

MY_IP=$(/usr/sbin/ifconfig | grep 'inet[^6]' | awk '{print $2}' |
	    sed 's/addr://' | grep -v 127.0.0.1 | grep -v 0.0.0.0 |
	    head -n 1)
echo My IP is ${MY_IP}.

ZOOKEEPER_MYID=${ZOOKEEPER_MYID:-1}

if [ "$ZOOKEEPERS" != "" ]
then

  ZOOKEEPERS=$(echo $ZOOKEEPERS | sed 's/,/ /g')

  i=1
  
  for zk in $ZOOKEEPERS
  do

    echo Configuring zookeeper $i $zk.

    if [ $i == ${ZOOKEEPER_MYID} ]
    then
      echo "server.$i=0.0.0.0:2888:3888" >> /usr/local/zookeeper/conf/zoo.cfg
    else
      echo "server.$i=$zk:2888:3888" >> /usr/local/zookeeper/conf/zoo.cfg
    fi
    i=$(($i + 1))

  done

  mkdir -p /data/zookeeper
  echo ${ZOOKEEPER_MYID:-1} > /data/zookeeper/myid

fi

/usr/local/zookeeper/bin/zkServer.sh start-foreground

